Refactor logging
ostis-ai/py-sc-kpm pull request #14
Opened 2022-09-19 13:34 UTC by FalseR20

2022-09-19 14:29 UTC, AlexandrZagorskiy requested changes

2022-09-19 14:50 UTC, FalseR20 commented on README.md
> +There is also method to confirm action class.
There is it usage [sum_agent_classic.py](docs/examples/sum_agent_classic.py)

2022-09-19 15:06 UTC, FalseR20 commented on README.md
> +#### Initialisation
Done

2022-09-19 15:06 UTC, FalseR20 commented on README.md
> +There is also method to confirm action class.
Done

2022-09-19 15:07 UTC, FalseR20 commented on README.md
> +There is also method to confirm action class.
I removed this line

2022-09-20 06:43 UTC, AlexandrZagorskiy approved these changes

2022-09-20 09:13 UTC, merged