Delete keynode
ostis-ai/py-sc-kpm pull request #28
Opened 2023-03-24 11:20 UTC by FalseR20

# Delete keynode from kb and ScKeynodes

## How to use

```python
del ScKeynodes["idtf_to_delete"]
```

2023-03-24 12:00 UTC, AlexandrZagorskiy requested changes

2023-03-24 12:24 UTC, FalseR20 commented on tests/test_keynodes.py
> +
Maybe we need to add refresh method that updates all stored keynodes addresses?

2023-03-24 12:52 UTC, AlexandrZagorskiy commented on tests/test_keynodes.py
> +
Okay, got it. So, we can implement **.pop()** method, if you want to propose logic as dict. I don't like the idea of providing deleting function as non-method. We can discuss this case in PM I think

2023-03-24 13:00 UTC, AlexandrZagorskiy commented on tests/test_keynodes.py
> +
Add refresh method looks like good idea, but naming is not clear, I prefer **sync()** method name for syncing with KB state. It's hard to understand when should I use it. Maybe it should be incapsulated and used automatically?

2023-03-27 09:22 UTC, FalseR20 commented on tests/test_keynodes.py
> +
I decided to use `delete` method name, it looks prettier and better.
`sync` method will be added in other PR

2023-03-27 13:24 UTC, AlexandrZagorskiy approved these changes
Update changelog

2023-03-27 15:14 UTC, merged