Add documentation in readme
ostis-ai/py-sc-kpm pull request #8
Opened 2022-09-02 13:41 UTC by FalseR20

2022-09-02 16:05 UTC, AlexandrZagorskiy approved these changes

2022-09-10 11:53 UTC, NikitaZotov requested changes
You need to agree on the description that was made. There are mistakes and some things are missing

2022-09-19 13:39 UTC, AlexandrZagorskiy approved these changes

2022-09-19 13:42 UTC, NikitaZotov approved these changes

2022-09-19 13:43 UTC, merged